<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use App\Song;

class SongsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $songsList = [
            [ //  [Alexandros]の曲
            'artist_id' => 1,
            'name' => [
                'I want u to love me',
                'Aoyama',
                '明日、またGOLD LYLIC',
                'Adventure',
                'アルペジオ',
                '言え',
                '今まで君が泣いた分取り戻そう',
                'Oblivion',
                'Kaiju',
                'Girl A',
                'Kick&Spin',
                'Kids',
                'Cat 2',
                "can't explain",
                'Kill Me If You Can',
                'Thunder',
                'city',
                'starrrrrrr feat.GEROCK',
                'Stimulator',
                'SNOW SOUND',
                'spy',
                'Swan',
                '閃光',
                '月色ホライズン',
                'This Is Teenage',
                'Travel',
                'Dog 3',
                'Dracula La',
                'Droshky!',
                '涙がこぼれそう',
                'Nawe, Nawe',
                'NEW WALL',
                'Buzz Off!',
                'Feel like',
                'Famous Day',
                'Forever Young',
                'For Freedom',
                'Boo!',
                'ムーンソング',
                "You're So Sweet & I Love You",
                'Rise',
                'Run Away',
                'Leaving Grapefruits',
                'ワタリドリ',
                'Wanna Get Out',
                "ワンテンポ遅れたMonster ain't dead",
                ]
            ],
            [ //  04 Limited Sazabysの曲
            'artist_id' => 2,
            'name' => [
                'swim',
                'Squall',
                'soup',
                'monolith',
                'Terminal',
                'Just',
                'My HERO',
                'fade',
                'Letter',
                'fiction',
                'Milestone',
                'Now here, No where',
                'Kitchen',
                'Utopia',
                'knife',
                'milk',
                'nem...',
                'Horizon',
                'Galapagos',
                'Montage',
                'escape',
                'climb',
                'Warp',
                'Lost my way',
                'Give me',
                'Feel',
                'message',
                'midnight cruising',
                'hello',
                'cubic',
                'Alien',
                'Jumper',
                'Do it Do it',
                'Chicken race',
                'drops',
                'Puzzle',
                'Grasshopper',
                'eureka',
                'mahoroba',
                '夕凪',
                'Brain sugar',
                'Buster call',
                'Night on',
                'Any',
                'Cycle',
                'medley',
                'Higher',
                'happiness',
                'days',
                'me?',
                'discord',
                'Standing here',
                'Wednesday',
                'memory lane',
                'Shine',
                'Touch your shape',
                'Telepathy',
                'labyrinth',
                'in out',
                'Password',
                'paradise',
                'teleport',
                'bless you',
                'Remember',
                'sacrifice',
                'fog',
                'ghost',
                'imaginary',
                'compact karma',
                'No way',
                'Sleepwalking',
                'MONSTER',
                'Silly Song',
                'My Life',
                'capture',
                ]
            ],
            [ //  10-FEETの曲
            'artist_id' => 3,
            'name' => [
                '1sec.',
                'RIVER',
                'ハローフィクサー',
                'その向こうへ',
                'アオ',
                'ヒトリセカイ',
                '2%',
                'シエラのように',
                'super stomper',
                'アンテナラスト',
                'goes on',
                'Fin',
                '蜃気楼',
                'VIBES BY VIBES',
                '太陽4号',
                'hammer ska',
                '風',
                '月 ~sound jammer せやな~',
                '火とリズム',
                'nil?',
                'ライオン',
                '1 size FITS ALL',
                'SHOES',
                'STONE COLD BREAK',
                'JUNGLES',
                'JUST A FALSE! JUST A HOLE!',
                ]
            ],
            [ //  9mm Parabellum Bulletの曲
            'artist_id' => 4,
            'name' => [
                'サクリファイス',
                'インフェルノ',
                'ハートに火をつけて',
                'ガラスの街のアリス',
                'Black Market Blues',
                '名もなきヒーロー',
                'Supernova',
                'Discommunication',
                'Answer And Answer',
                'Cold Edge',
                'The Revolutionary',
                'Termination',
                'Punishment',
                '黒い森の旅人',
                '泡沫',
                'Lost!!',
                'Living Dying Message',
                'キャンドルの灯を',
                ]
            ],
            [ //  a crowd of rebellionの曲
            'artist_id' => 5,
            'name' => [
                'M1917',
                'ZENITH',
                '無罪者',
                'Ill',
                'DISTRESS',
                'Nex:us',
                'リビルド',
                'The Crow',
                'Anemone',
                'hAngedmAn_A',
                "She'll Never Forgive To Be Insulted.",
                'Hello, Mr. Judgement.',
                'B.A.I.B',
                'II:α→Ω:II',
                'Crocus',
                'QED',
                'Black Philosophy Bomb',
                ]
            ],
            [ //  a flood of circleの曲
            'artist_id' => 6,
            'name' => [
                '北極星のメロディー',
                '花',
                'まだ世界は君のもの',
                'ミッドナイト・クローラー',
                'Dancing Zombiez',
                'アカネ',
                '青く塗れ',
                'Beast Mode',
                'シーガル',
                "I'M FREE",
                'クレイジー・ギャンブラーズ',
                ]
            ],
            [ //  AC / DCの曲
            'artist_id' => 7,
            'name' => [
                'Thunderstruck',
                'Back In Black',
                'Highway to Hell',
                'You Shook Me All Night Long',
                'Hells Bells',
                ]
            ],
            [ //  Acid Black Cherryの曲
            'artist_id' => 8,
            'name' => [
                'イエス',
                'Black Cherry',
                '黒猫 ~Adult Black Cat~',
                '眠り姫',
                '愛してない',
                'SPELL MAGIC',
                'シャングリラ',
                ]
            ],
            [ //  ACIDMANの曲
            'artist_id' => 9,
            'name' => [
                '赤橙',
                'Rebirth',
                '造花が笑う',
                'innocence',
                'スロウレイン',
                '式日',
                ]
            ],
            [ //  Adoの曲
            'artist_id' => 10,
            'name' => [
                '踊',
                '阿修羅ちゃん',
                'うっせぇわ',
                '心という名の不可解',
                'ギラギラ',
                'レディメイド',
                '花火',
                '夜のピエロ',
                '会いたくて',
                'マザーランド',
                ]
            ],
            [ //  ASIAN KUNG-FU GENERATIONの曲
            'artist_id' => 16,
            'name' => [
                '遥か彼方',
                'リライト',
                'アフターダーク',
                'Re:Re:',
                'ブラッドサーキュレーター',
                'ソラニン',
                '君という花',
                'エンパシー',
                'それでは、また明日',
                'ムスタング',
                '未来の破片',
                ]
            ],
            [ //  ELLEGARDENの曲
            'artist_id' => 54,
            'name' => [
                'ジターバグ',
                'Missing',
                'Red Hot',
                'Supernova',
                '高架線',
                'Marry Me',
                'スターフィッシュ',
                'The Autumn Song',
                '風の日',
                'Make A Wish',
                'Space Sonic',
                'モンスター',
                'No.13',
                '虹',
                'Salamander',
                'Fire Cracker',
                'TV Maniacs',
                ]
            ],
            [ //  KANA-BOONの曲
            'artist_id' => 86,
            'name' => [
                'シルエット',
                'ないものねだり',
                'スターマーカー',
                'バトンロード',
                'フルドライブ',
                'Fighter',
                '盛者必衰の理、お断り',
                ]
            ],
            [ //  MONGOL800の曲
            'artist_id' => 111,
            'name' => [
                '小さな恋のうた',
                'あなたに',
                '月灯りの下で',
                '矛盾の上に咲く花',
                '琉球愛歌',
                'Song for you',
                ]
            ],
            [ //  ONE OK ROCKの曲
            'artist_id' => 132,
            'name' => [
                'The Beginning',
                'Renegades',
                '完全感覚Dreamer',
                'Clock Strikes',
                'Stand Out Fit In',
                'Broken Heart of Gold',
                'Wasted Nights',
                'Wherever you are',
                'Re:make',
                'C.h.a.o.s.m.y.t.h.',
                'Mighty Long Fall',
                'キミシダイ列車',
                'Cry out',
                'Deeper Deeper',
                'Liar',
                'アンサイズニア',
                'じぶんROCK',
                'ONION!',
                'Ending Story??',
                ]
            ],
            [ //  THE ORAL CIGARETTESの曲
            'artist_id' => 176,
            'name' => [
                '狂乱 Hey Kids!!',
                'BLACK MEMORY',
                'MACHINEGUN',
                '気づけよBaby',
                'ワガママで誤魔化さないで',
                'Red Criminal',
                '容姿端麗な嘘',
                'A-E-U-I',
                '5150',
                'カンタンナコト',
                'エイミー',
                '起死回生STORY',
                'CATCH ME',
                'ReI',
                '大魔王参上',
                'Uh...Man',
                ]
            ],
            [ //  スピッツの曲
            'artist_id' => 226,
            'name' => [
                'ロビンソン',
                '空も飛べるはず',
                'チェリー',
                '楓',
                '春の歌',
                '正夢',
                '君が思い出になる前に',
                '魔法のコトバ',
                ]
            ],
            [ //  マキシマム ザ ホルモンの曲
            'artist_id' => 239,
            'name' => [
                '恋のメガラバ',
                '「F」',
                '爪爪爪',
                '絶望ビリー',
                'ぶっ生き返す!!',
                '恋のスペルマ',
                'シミ',
                'アカギ',
                "What's up, people?!",
                '便所サンダルダンス',
                'ROLLING1000tOON',
                'え・い・り・あ・ん',
                '鬱くしき人々の歌',
                'ロック番狂わせ',
                'mygirl',
                'ポリスマンベンツ',
                'ロックンロール・チェーンソー',
                'Mrブギータンブリンマン',
                ]
            ],
            [ //  MR.BIGの曲
            'artist_id' => 113,
            'name' => [
                'To Be with You',
                'Wild World',
                'Take Cover',
                'Daddy, Brother, Lover, Little Boy [The Electric Drill Song]',
                'Green-Tinted Sixties Mind',
                'Addicted to That Rush',
                'Stay Together',
                'Colorado Bulldog',
                'Take A Walk',
                ]
            ],
            [ //  エレファントカシマシの曲
            'artist_id' => 202,
            'name' => [
                '今宵の月のように',
                '俺たちの明日',
                '桜の花、舞い上がる道を',
                '風と共に',
                '悲しみの果て',
                '翳りゆく部屋',
                '笑顔の未来へ',
                'RAINBOW',
                '風に吹かれて',
                'ズレてる方がいい',
                'Easy Go',
                'リッスントゥザミュージック',
                ]
            ],
            [ //  Hi-STANDARDの曲
            'artist_id' => 75,
            'name' => [
                'STAY GOLD',
                'THE SOUND OF SECRET MINDS',
                'ANOTHER STARTING LINE',
                'DEAR MY FRIEND',
                "CAN'T HELP FALLING IN LOVE",
                'MY FIRST KISS',
                'All Generations',
                'STARRY NIGHT',
                'The Gift',
                'FIGHTING FISTS, ANGRY SOUL',
                'MAXIMUM OVERDRIVE',
                'GROWING UP',
                'NEW LIFE',
                "CALIFORNIA DREAMIN'",
                ]
            ],
        ];

        foreach ($songsList as $songs) {
            foreach ($songs['name'] as $song) {
                Song::create(['name' => $song, 'artist_id' => $songs['artist_id']]);
            }
        }
    }
}
